# Generated by Django 5.2.5 on 2025-09-03 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('author', models.CharField(blank=True, default='Team Fort Seva', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cover_image', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('district', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, help_text='Address or short location text', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('clean', 'Clean'), ('needs_cleaning', 'Needs Cleaning'), ('under_renovation', 'Under Renovation')], default='needs_cleaning', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=32)),
                ('photos', models.TextField(blank=True, help_text='Comma separated image URLs')),
                ('fort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.fort')),
            ],
        ),
    ]
