# Generated by Django 5.2.5 on 2025-09-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_fort_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fort',
            name='image_url',
            field=models.ImageField(upload_to='../frontend/public'),
        ),
    ]
