# Generated by Django 5.2.5 on 2025-09-04 06:54

import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_fort_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='fort',
            options={'ordering': ['name'], 'verbose_name': 'Fort', 'verbose_name_plural': 'Forts'},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Volunteer', 'verbose_name_plural': 'Volunteers'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='fort',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='fort',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='fort',
            name='longitude',
        ),
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='article',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/banners/'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fort',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fort',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='forts/main/'),
        ),
        migrations.AddField(
            model_name='fort',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, unique=True),
        ),
        migrations.AddField(
            model_name='fort',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='availability',
            field=models.CharField(blank=True, help_text='e.g. Weekends, Weekdays, Evenings', max_length=120),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='interests',
            field=models.CharField(choices=[('cleaning', 'Fort Cleaning'), ('renovation', 'Renovation & Maintenance'), ('heritage', 'Heritage Awareness'), ('event', 'Event Management'), ('other', 'Other')], default='cleaning', help_text='Area volunteer is most interested in', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='fort',
            name='location',
            field=models.CharField(blank=True, help_text='Village/area or short location text', max_length=255),
        ),
        migrations.AlterField(
            model_name='fort',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='fort',
            name='status',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('clean', 'Clean'), ('needs_cleaning', 'Needs Cleaning'), ('under_renovation', 'Under Renovation')], max_length=200),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='FortImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='forts/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('fort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.fort')),
            ],
        ),
    ]
